### ISSUE TITLE
distributors GitHub team?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#59] opened 2018-02-05 18:57 UTC
From [a comment](https://github.com/nodejs/TSC/issues/301#issuecomment-362839172) from @kapouer:

> i did not find any team of "distributors": debian, fedora, etc... maybe it would be a good idea to create one. (and i did not find where to open an issue about that fact).

Is there already one? If not, should there be one? I believe @nodejs/build has talked about this at least once but I don't know what the outcome was.

@nodejs/tsc @nodejs/community-committee

**Comment by mhdawson** [comment] 2018-02-05 21:40
We had a similar discussion around "bundlers" like electron but I don't think we came to a final resolution in that discussion.

**Comment by gibfahn** [comment] 2018-02-06 10:28
+1 on having one, I have felt the need to ping this group in the past, and I assume others have too. IDK what the naming should be, having electron and distro people in seems logical.

If someone wants to PR the team into the [Contributing Extras](https://github.com/nodejs/node/blob/master/doc/onboarding-extras.md#who-to-cc-in-issues) section, then let's create the team.

**Comment by ljharb** [comment] 2018-02-06 16:32
Would version managers be considered a distributor?

**Comment by Trott** [comment] 2018-02-06 18:11
> Would version managers be considered a distributor?

Probably makes sense to start with a broad group where version managers would be included. Then, if experience indicates that something more granular is needed, we can split them into subteams at a later date.

**Comment by ljharb** [comment] 2018-02-06 18:15
Makes sense. I'm just not sure what definition of a "distributor" wouldn't apply to version managers, although the reverse is not necessarily true.

**Comment by mhdawson** [comment] 2018-02-06 19:08
I'll volunteer to PR into the Contributing Extras section, unless somebody else wants to do it.

**Comment by gibfahn** [comment] 2018-02-07 14:57
>Makes sense. I'm just not sure what definition of a "distributor" wouldn't apply to version managers, although the reverse is not necessarily true.

The original list seems to be mostly people who do their own builds of node (electron + Linux distros), so might not be relevant to package managers. Agreed that in that case distributor is maybe not a great name.

No issue with anyone who wants to being involved in any case.

**Comment by mhdawson** [comment] 2018-02-07 15:26
What do people think of "bundlers".  Teams that either bundle node into their OS distributions or into their projects or products directly?

**Comment by ljharb** [comment] 2018-02-07 16:54
That term wouldn’t include Debian, Fedora, etc, would it?

**Comment by mcollina** [comment] 2018-02-07 21:30
Would that include docker image builders?

**Comment by mhdawson** [comment] 2018-02-08 14:49
@ljharb it depends on how you define "bundlers"  I tried to include them in my definition above but maybe it needs to be more explicit.  How about:

Bundlers:
Teams that bundle node in some form (community binaries, custom built binaries, or source code) into their OS distributions, projects or products.

**Comment by mhdawson** [comment] 2018-02-08 14:50
@mcollina I think it would include docker images builds.

**Comment by ljharb** [comment] 2018-02-08 18:43
Right, but Debian etc don’t bundle node - they bundle a package manager that can *install* node, but that’s not the same thing.

**Comment by mhdawson** [comment] 2018-02-08 19:59
Maybe we can call the group "bundlers and installers":
Members do one of the following:
* bundle node in some form (community binaries, custom built binaries, or source code) into their OS distributions, projects or products or
* build installers that allow the installation of Node.js binaries

**Comment by ljharb** [comment] 2018-02-09 02:59
That then would also include all version managers?

**Comment by Elexy** [comment] 2018-02-09 06:33
I am involved in https://github.com/nearform/nodejs-distribution, just curious if I could be of value in such a group.
What would the group be responsible for?
What are the goals / deliverables?
Again, just curious :-)

**Comment by mhdawson** [comment] 2018-02-09 16:14
@ljharb I think so.

@Elexy we are just talking about setting up a github "team" were we can add people that would like to be notified through @nodejs/bundlersandinstallers or something like that when we have discussions/news that might impact them.

**Comment by bnb** [comment] 2018-02-13 02:01
FWIW: @chrislea has some pretty institutional knowledge of Node.js distributions for Debian and RHEL, having built the images available at https://github.com/nodesource/distributions for several years now. I won't raise his hand for him, but he may be interested in participating as well ❤️

**Comment by chrislea** [comment] 2018-02-13 02:08
NodeSource already makes installers / packages for the most popular distros, and we're revamping making Docker bits as well right now. So I'm not sure if the goals here are something different than that, but there's already been a fair amount of work done.

Happy to help out with whatever I can though, just let me know what I can do.

**Comment by mhdawson** [comment] 2018-02-15 00:01
@chrislea this is not about starting an effort to do something new, only to have a team we can include in discussions that might come up.

**Comment by mhdawson** [comment] 2018-02-15 00:01
@ljharb you ok with my last description of what members the team will cover?  If so I'll try to think of a better name and then open a PR to add.

**Comment by ljharb** [comment] 2018-02-15 00:25
Yes. If so, please make the version manager working group team a child team of the larger team you intend to create :-)

**Comment by mhdawson** [comment] 2018-03-02 20:51
PR to addnew team https://github.com/nodejs/node/pull/19098

**Comment by mhdawson** [comment] 2018-03-05 23:39
Landed new team name  in https://github.com/nodejs/node/pull/19098  as delivery-channels

**Comment by mhdawson** [comment] 2018-03-05 23:43
https://github.com/orgs/nodejs/teams/version-management is now a child of the new team https://github.com/orgs/nodejs/teams/delivery-channels

**Comment by mhdawson** [comment] 2018-03-05 23:44
@Trott did you have any contacts from the distributions that we should be adding to start off?

**Comment by ljharb** [comment] 2018-03-05 23:52
@mhdawson hm, it doesn't seem like version-management is a child of delivery-channels yet

**Comment by Trott** [comment] 2018-03-06 00:00
> @Trott did you have any contacts from the distributions that we should be adding to start off?

@kapouer expressed interest.

**Comment by Trott** [comment] 2018-03-06 00:01
> @mhdawson hm, it doesn't seem like version-management is a child of delivery-channels yet

@ljharb I've made it so, just now.

**Comment by Trott** [comment] 2018-03-06 00:03
@mhdawson You probably don't want to add members to @delivery-channels but instead create subteams and add members there. This way, people can have the choice of notifying OS package managers (yum, for example) vs. Node.js-specific version managers (nvm, for example).

**Comment by Trott** [comment] 2018-03-06 00:05
(Deleted my previous comment, it can always be done at a later date if it proves to be a desirable feature, otherwise there's an argument to be made about avoiding proliferation of Yet More Teams if they're not needed. I'll delete this comment too.)

**Comment by kapouer** [comment] 2018-03-06 00:50
Interest confirmed. For fedora i don't know who is involved. Maybe @sgallagher knows.

**Comment by Trott** [comment] 2018-03-06 00:56
(Added @kapouer.)

**Comment by rogerwang** [comment] 2018-03-06 06:10
Please add me and @GnorTech. They are maintainers of NW.js which is a large downstream of Node.

**Comment by Elexy** [comment] 2018-03-06 06:11
Confirming my interest since I am responsible for building nearForm's Node.js images for Docker hub and the Red Hat Catalog.

**Comment by sgallagher** [comment] 2018-03-06 15:31
For Fedora, I'm probably the primary contact. However, you could also add `nodejs@lists.fedoraproject.org` which is a mailing list that includes all the people involved in packaging Node.js and NPM modules in Fedora.

**Comment by ljharb** [comment] 2018-03-06 15:35
@sgallagher i believe it’s limited to Github accounts; it’s a team, not a mailing list.

**Comment by mhdawson** [comment] 2018-03-06 19:42
@Trott I was pretty sure I had added it as a child, was it obvious what I had done wrong?  I went to the version-management team and made the parent the new team.  Did I just manage not to save that or was there some other step I need to do?

**Comment by Trott** [comment] 2018-03-06 22:51
>  was it obvious what I had done wrong?

Nope.

> Did I just manage not to save... ? 

Probably. I've done that once or twice.

**Comment by Trott** [comment] 2018-03-06 23:04
@mhdawson If it's OK with you, I'll leave it to you to add the additional people mentioned in this thread if you deem it appropriate. I feel like you are likely to have more direct involvement than me so that seems to make sense. 

(Just making sure you're not assuming I'm handling it.)

**Comment by mhdawson** [comment] 2018-03-07 23:04
@Trott ack.  I belive I've added everybody who's expressed interest so far.

**Closed** 2018-03-08 03:25 UTC
