### ISSUE TITLE
Enable Org-wide discussions and disable Team Discussions

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#770] opened 2023-02-27 16:01 UTC
GitHub is [sunsetting team-based discussions](https://github.blog/changelog/2023-02-08-sunset-notice-team-discussions/) in favour of [org-wide discussions](https://github.blog/2022-04-12-whats-new-in-github-discussions-organization-discussions-polls-and-more/) which is GitHub Discussions.

**I'd like to suggest for us to:**

- Create Org-wide discussions and configure them (e.g., categories and stuff)
- Disable Team-based discussions as they always had poor visibility.
- Move relevant discussions that are still open to the org-wide discussions (GitHub has a built-in feature for moving this).

Org-wide Discussions will give us a better reach when making announcements or when we want to have essential discussions involving the Community. I see it as a great place for us to:

- Post relevant announcements to contributors
- Post relevant announcements to our community/user-base (such as security releases)
- Post relevant discussions/threads for new features, or upcoming critical changes

Regardless of the points above regarding what we could use the org-wide discussions for, this issue asks to, for now, enable org-wide discussions and, if the TSC is okay with it, disable team-based ones.

cc @nodejs/tsc

**Comment by nschonni** [comment] 2023-02-27 16:06
Duplicate of https://github.com/nodejs/admin/issues/679
Team discussions thread https://github.com/nodejs/TSC/issues/1340

**Closed** 2023-03-16 11:56 UTC
