### ISSUE TITLE
Audit Google account access

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/admin#389] opened 2019-07-17 17:32 UTC
I dunno if anyone's kept up exactly but, _a lot_ of people have access to the google account, which hosts the youtube, etc.

We should audit who still need access because there must be upwards of 30 or so people by now, which could pose a liability.

**Comment by keywordnew** [comment] 2019-07-23 04:39
Totally!

Is there a single source of truth for Google access records? I know that, at least for Zoom accounts, we don't have that. Brian has been starting to systematize that with some shared LastPass vaults.

**Comment by mhdawson** [comment] 2019-07-23 13:53
If it's just the Google Youtube account then through the UI you can see the list of people who have access.

**Comment by Fishrock123** [comment] 2019-07-24 19:01
Ok so, here's the list(s) by role, as of 24/07/2019:

## "Primary Owner"
| Name | GitHub | Why |
|----|----|----|
| Brian Warner | ? | LF |

## Owner
| Name | GitHub | Why |
|----|----|----|
| Adam Miller | amiller-gh | CC |
| Amanda Ennis | OfficialLinuxAmanda (?) | LF (?) |
| James Snell | jasnell | TSC |
| Jeremiah Senkpiel | Fishrock123 | TSC |
| Michael Dawson | mhdawson | TSC |
| Rachel Romoff | RRomoff (?) | ? |
| Rich Trott | trott | TSC |
| Rod Vagg | rvagg | Build WG ?, Former TSC |
| Tracy Hinds | hackygolucky | CC |

## Manager
| Name | GitHub | Why |
|----|----|----|
| Ahmad Bamieh | bamieh | CC |
| Ahmad Nassri | ahmadnassri | User-Feedback |
| Alexis Campailla | orangemocha | Former TSC |
| Ann Marie Tonog | AnnMarieTonog (?) | ? |
| Bethany Griggs | BethGriggs | ? |
| Chris Dickinson | chrisdickinson | Former TSC |
| Christopher Hiller | boneskull | ? |
| Colin Ihrig | cjihrig | TSC |
| Dan Shaw | dshaw | User-Feedback |
| Daniel Bevenius | danbev | TSC |
| Eldar Djafarov | edjafarov (?) | ? |
| Franziska Hinkelmann | fhinkel | TSC |
| Gabriel Schulhof | gabrielschulhof | TSC |
| Gireesh Punam | gireeshpunathil (?) | TSC |
| Johan Bergström | jbergstroem | Build WG |
| Josh Gavant | joshgav | Former TSC |
| Lara Taback | --- | ? |
| Matteo Collina | mcollina | TSC |
| Mike Kaufman | mike-kaufman | Diagnostics WG |
| Myles Borins | MylesBorins | TSC |
| Patrick Mueller | pmuellr | Former Diag WG |
| Peter Marton | hekike | Diagnostics WG |
| Sam Roberts | sam-github | TSC |
| Sarah Conway | SarahKConway | LF ? |
| Tierney Cyren | bnb | CC |
| Timothy Arthur | timzing (?) | ? |
| Todd Benzies | tbenzies | LF |
| Tracy Lee | ladyleet | ? |
| Uttam C Pawar | uttampawar | ? |
| William Kapke | williamkapke | CC |
| jernstfriedman_old@linuxfoundation.org | --- | Looks deactivated | 

## Invites
| Name | GitHub | Why |
|----|----|----|
| gabriel.schulhof@intel.com | Manager Invite | --- | --- |

**Comment by Fishrock123** [comment] 2019-07-24 19:04
I might not have gotten everything correct there so please feel free to edit it (but update the date if you do).

I think we can start some clean-up by:

- Removing the deactivated account
- Clearing Gabriel's apparent second invite
- Removing access from anyone who was "former ..." and is no longer active.
- Removing access from anyone we can't identify, if anyone falls into that category

**Comment by richardlau** [comment] 2019-07-24 19:08
> 
> 
> Ok so, here's the list(s) by role, as of 24/07/2019:
> ## Manager
> | Name | GitHub | Why |
> |-|-|-|
> | Bethany Griggs | BethGriggs | ? |

@BethGriggs runs the Release WG meetings.

**Comment by Fishrock123** [comment] 2019-07-24 23:51
cc @nodejs/tsc @nodejs/community-committee

**Comment by cjihrig** [comment] 2019-07-25 00:03
uttampawar uses the access for Benchmarking WG meetings.

+1 to removing all of the "former"s and the deactivated account. Maybe ping anyone with a ? after a few more days before removing them.

**Comment by Trott** [comment] 2019-07-25 03:16
I think @boneskull uses it for the Tooling meetings but I could be wrong.

**Comment by WaleedAshraf** [comment] 2019-07-25 09:09
Rachel Romoff is from LF and participates in most of CommComm meetings.
Tracy Lee is from thisdot and also participates in CommComm meetings.

I'm not sure which meetings they host.

**Comment by boneskull** [comment] 2019-07-25 14:03
yep I use it for tooling group meetings

**Comment by mcollina** [comment] 2019-07-25 15:05
> +1 to removing all of the "former"s and the deactivated account. Maybe ping anyone with a ? after a few more days before removing them.

Same! +1.

**Comment by mhdawson** [comment] 2019-07-25 20:36
Update a few based on what I know.

+1 to 
>+1 to removing all of the "former"s and the deactivated account. Maybe ping anyone with a ? after a few more days before removing them.

**Comment by Fishrock123** [comment] 2019-07-26 17:28
Ok I removed the following people: 

| Name | GitHub | Why |
|----|----|----|
| Alexis Campailla | orangemocha | Former TSC |
| Chris Dickinson | chrisdickinson | Former TSC |
| Patrick Mueller | pmuellr | Former Diag WG |
| jernstfriedman_old@linuxfoundation.org | --- | Looks deactivated | 
| gabriel.schulhof@intel.com | Manager Invite | --- | --- |

**Comment by Fishrock123** [comment] 2019-07-26 17:31
Does anyone know if these people presently need access?

| Name | GitHub | Why |
|----|----|----|
| Eldar Djafarov | edjafarov (?) | ? |
| Lara Taback | --- | ? |
| Sarah Conway | SarahKConway | LF ? |
| Timothy Arthur | timzing (?) | ? |
| Todd Benzies | tbenzies | LF |

**Comment by RRomoff** [comment] 2019-07-26 18:50
You can keep Todd Benzies and delete Sarah Conway. Thank you!

**Comment by Fishrock123** [comment] 2019-07-26 20:19
Ok, done.

**Comment by Fishrock123** [comment] 2019-07-29 17:38
Neither _Eldar Djafarov_ or _Timothy Arthur_ appear to be members of the Node.js github org, so I plan to also remove them. Should we let them know somehow?

Ditto for _Lara Taback_ but also I can't find her github / any way to contact her. (The interface does not expose google email addresses, unfortunately.)

**Comment by mhdawson** [comment] 2019-07-29 22:26
I think Laura used to work at the Foundation, but I don't think I've talked to her in quite a while.  I think removing should be ok.

**Comment by bnb** [comment] 2020-04-28 17:32
Is there any further steps here? If so, what are they? If not, can we close this?

**Comment by Fishrock123** [comment] 2020-04-28 17:37
This kind of audit should be done yearly at least, imo.

I can be removed from the google account now too.

**Comment by Trott** [comment] 2020-04-30 13:09
> This kind of audit should be done yearly at least, imo.

It will probably be forgotten unless it is made someone's responsibility. "An audit will happen yearly" means it probably won't happen. "The CommComm Chair will perform an audit or identify someone to perform an audit in June of every year" is more likely to actually happen.

The question is: Who is the best person or people to take on this duty? Foundation folks? CommComm? TSC? Someone else?

**Comment by mhdawson** [comment] 2020-05-04 19:32
I think adding it to the list of things for either the CommComm or TSC chair makes sense.  I think it should be up to whoever we choose, to ensure it happens either by finding a volunteer or doing it themselves.

**Comment by mhdawson** [comment] 2020-05-07 20:20
@brianwarner volunteered to take this on if we want the foundation to take this on.

**Comment by mhdawson** [comment] 2020-05-07 20:21
@nodejs/community-committee are you ok with @brianwarner/foundation handling this?

**Comment by brianwarner** [comment] 2020-05-07 20:24
Proposed process from the TSC meeting:
* Brian to generate a list of people with access
* Brian to work with chairs of TSC and CommComm to do initial filtering of who should be on the list
* Any names not tagged in the first round will be distributed to the broader TSC and CommComm for consideration
* Any names not tagged in either round will be pruned from the account.

**Comment by mhdawson** [comment] 2020-05-08 17:45
+1 to the suggested process.

**Comment by amiller-gh** [comment] 2020-05-08 19:47
Hi all, briefly surfacing from my startup-life exile to +1 the above process and to say I also don't need access any more 🙏 

Miss you all!

**Comment by ahmadawais** [comment] 2020-05-08 21:16
+1 to @brianwarner's suggestions.

**Comment by mhdawson** [comment] 2020-05-21 21:28
@brianwarner seems like your proposal looks good to people, can we move to the next step?

**Comment by brianwarner** [comment] 2020-05-21 21:39
Sounds good, it's good timing because I'm doing the same thing right now for jQuery. I'll build a list of people who have accounts in gsuite, or are on google groups mailing lists, or are currently owners/content managers on YouTube.

**Comment by bnb** [comment] 2020-05-28 16:20
Removing the agenda item for now since it seems like there's nothing to be done from CommComm's side currently.

**Comment by mhdawson** [comment] 2020-06-15 23:22
@brianwarner just making sure this is still on your list.

**Comment by mhdawson** [comment] 2021-01-14 22:16
Generated list of people to be removed, confirmed with Tierney and did the removal. Closing.

**Closed by mhdawson** 2021-01-14 22:16 UTC
Labels: tsc-agenda
